### ISSUE TITLE
Missing configuration for maven wrapper

### ISSUE THREAD

**Issue by Boereck** [gematik/DEMIS-validation-service#5]
The maven wrapper scripts (`/mvnw` and `/mvnw.cmd`) are checked in, but the content of the `/.mvn` directory is not checked in. This will cause the wrapper to fail when being called. The jar file can be excluded (there is a [line](https://github.com/gematik/DEMIS-validation-service/blob/673c81bd8a3a5419ab4bb27a6627e260c1a06a78/.gitignore#L3) in the `.gitignore` file which has to be negated), but the `/.mvn/wrapper/maven-wrapper.properties` file has to be checked in. If the Jar file is not present, the script will download it from the location specified in the `maven-wrapper.properties`.

By the way: In the build instructions of the `README.md` file, the example maven invocation is calling maven directly, instead of the wrapper. It might be better to use the wrapper in the example, so that the configured version of maven is used. It would also be great to specify that a JDK 17 is needed to build the project (maybe with a suggestion which distribution to use).

Since it may cause conflicts if someone else checks in a maven-wrapper configuration it may be best if the original authors check in their configuration file.

**Comment by madduci** [comment]
Hello @Boereck 

thank you for your report, we have decided to remove completely the maven wrapper, since we don't use it internally (resolved with #6) and has never been planned to be distributed on GitHub within this repository.
